export const FILTER_BTN_TESTID = 'FILTER_BTN_TESTID';
export const SEARCH_INPUT_TXT_TESTID = 'SEARCH_INPUT_TXT_TESTID';
export const LOADER_INDICATION_TESTID = 'LOADER_INDICATION_TESTID';
export const FILTER_SCREEN_ERROR_TEXT_ID = 'FILTER_SCREEN_ERROR_TEXT_ID';
export const RADIO_BUTTON_TESTID = 'RADIO_BUTTON_TESTID';
export const USER_COMPONENT_NAME_TESTID = 'USER_COMPONENT_NAME_TESTID';
export const USER_COMPONENT_ROLE_TESTID = 'USER_COMPONENT_ROLE_TESTID';